apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.6.0 (e4adfef)
  creationTimestamp: null
  labels:
    io.kompose.service: tracing-server
  name: tracing-server
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: tracing-server
    spec:
      containers:
      - command: ["/bin/sh", "-c"]
        args: ["java -Djava.security.egd=file:/dev/./urandom -jar /app.jar"]
        image: mszarlinski/spring-petclinic-tracing-server
        name: tracing-server
        ports:
        - containerPort: 9411
        resources: {}
      restartPolicy: Always
status: {}
